/*
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
namespace: logging
data:
  logstash.conf: |
    input {
      udp {
        port => 5000
        codec => "json"
      }
    }
    filter {
      if [type] == "nginx-access" {
        grok {
          match => { "message" => "%{COMBINEDAPACHELOG}" }
        }
      }
    }
    output {
      elasticsearch {
        hosts => ["elasticsearch.logging.svc.cluster.local:9200"]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: config-volume
        configMap:
          name: logstash-config
*/