/*
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: enterprise-prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
dkind: ServiceMonitor
metadata:
  name: enterprise-service-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: enterprise-app
  endpoints:
  - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: Grafana
metadata:
  name: enterprise-grafana
spec:
  resources:
    requests:
      memory: 200Mi
*/