name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build Docker image
      run: |
        docker build -t myregistry.com/enterprise-app/frontend:latest -f frontend/Dockerfile .
        docker build -t myregistry.com/enterprise-app/backend:latest -f backend/Dockerfile .
    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login myregistry.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push myregistry.com/enterprise-app/frontend:latest
        docker push myregistry.com/enterprise-app/backend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ${{ secrets.K8S_USERNAME }}
        key: ${{ secrets.K8S_SSH_KEY }}
        script: |
          kubectl apply -f k8s/